iSTLDevEx/iSTLDevEx/Controllers/OperatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iSTLDevEx.DAL;
using iSTLDevEx.Utilities;
using System.Web.Security;

namespace iSTLDevEx.Controllers
{
    [Authorize]
    public class OperatorController : Controller
    {
        private SMSSysEntities dbContext;
        private CurrentUser _user;

        public OperatorController()
        {
            dbContext = new SMSSysEntities();
            var usr = Membership.GetUser();
            _user = new CurrentUser(dbContext, usr);
            var oprID = _user.OperatorID;
        }

        protected override void Dispose(bool disposing)
        {
            dbContext.Dispose();
            base.Dispose(disposing);
        }

        // GET: Operator
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult JsonOperatorAgentList()
        {
            //var userInDB = dbContext.T_ReceivedBetArc
            //    .OrderByDescending(x=>x.ReceivedDate)
            //    .ToList();
            //var userInDB = dbContext.T_ReceivedBet.OrderByDescending(x => x.ReceivedDate).ToList();
            var operatorID = _user.OperatorID;
            var userInDB = dbContext.T_ReceivedBet
                .Where(x=>x.OperatorCode == operatorID)
                .OrderByDescending(x => x.ReceivedDate)
                .ToList();
            return new JsonNetResult() { Data = userInDB };
        }


    }
}

iSTLDevEx/iSTLDevEx/Views/Operator/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div style="padding-top:50px">
    <h2>Recieved Bets</h2>
    <hr />
    <div class="">
        <table id="tblOperatorAgentList" class="table table-bordered table-responsive table-hover table-striped">
            <thead>
                <tr>
                    <th>Date Recieved</th>
                    <th>Agent Name</th>
                    <th>Operator Name</th>
                    <th>Draw Time</th>
                    <th>Combination</th>
                    <th>Str Amt</th>
                    <th>Ramble Amt</th>
                </tr>
            </thead>
            <tbody></tbody>

        </table>
    </div>
</div>




<script>
    $(document).ready(function () {
        $.fn.dataTable.moment('DD-MMM-YYYY HH:mm:ss');
        var table = $("#tblOperatorAgentList").DataTable({
            //bLengthChange: false,
            ////"bFilter": true,
            //bInfo: true,
            //bAutoWidth: true,
            pageLength: 50,
            order: [[ 0, "desc" ]],
            dom: 'Bfrtip',
            ajax: {
                url: '@Url.Action("JsonOperatorAgentList", "Operator")',
                type: 'GET',
                dataSrc: "",
            },
            columns: [
                {
                    data: "ReceivedDate",
                    render: function (data, type, drow) {
                        return moment(data.toString()).format("DD-MMM-YYYY HH:mm:ss");
                    }
                },
                { data: "AgentName" },
                { data: "OperatorName" },
                { data: "ForDraw" },
                { data: "CombinationNo" },
                { data: "StraightAmtBet" },
                { data: "RambolAmtBet" },
            ],
            //buttons: [
            //{
            //    text: 'Refresh',
            //    action: function (e, dt, node, config) {
            //        table.ajax.reload();
            //    }
            //}
            //]
            buttons: [
                {
                    text: 'Refresh',
                    className: "btn btn-success"
                }

            ]

        });

        //For Auto Refresh every 120 second
        //setInterval(function () {
        //    table.ajax.reload();
        //}, 120000);
    });
</script>